/** Expanded B2B business niches for matrix autocomplete (slug, display label). */
export const BUSINESS_NICHES: Array<[string, string]> = [
  // Marketing, comunicação e eventos
  ["agencias_publicidade", "Agências de publicidade"],
  ["marketing_digital", "Agências de marketing digital"],
  ["comunicacao_visual", "Comunicação visual"],
  ["graficas", "Gráficas"],
  ["graficas_rapidas", "Gráficas rápidas"],
  ["serigrafia_estamparia", "Serigrafia e estamparia"],
  ["brindes_corporativos", "Brindes corporativos"],
  ["eventos_corporativos", "Organização de eventos corporativos"],
  ["assessoria_imprensa", "Assessoria de imprensa"],
  ["producao_conteudo", "Produção de conteúdo"],
  ["design_grafico", "Design gráfico"],
  ["fotografia", "Fotografia"],
  ["producao_video", "Produção audiovisual"],
  ["studio_podcast", "Estúdios de podcast"],
  ["agencia_influencers", "Agências de influenciadores"],
  ["relacoes_publicas", "Relações públicas"],
  // Tecnologia e digital
  ["tecnologia", "Empresas de tecnologia"],
  ["software", "Software e SaaS"],
  ["desenvolvimento_software", "Desenvolvimento de software"],
  ["apps_mobile", "Desenvolvimento de aplicativos"],
  ["provedores_internet", "Provedores de internet"],
  ["hosting_cloud", "Hospedagem e cloud"],
  ["ciberseguranca", "Cibersegurança"],
  ["suporte_ti", "Suporte e assistência de TI"],
  ["ecommerce", "E-commerce"],
  ["marketplaces", "Marketplaces"],
  ["automacao_comercial", "Automação comercial"],
  ["crm_erp", "Implementação de CRM e ERP"],
  ["inteligencia_artificial", "Inteligência artificial e dados"],
  ["iot", "Internet das coisas (IoT)"],
  ["telecomunicacoes", "Telecomunicações"],
  // Saúde e bem-estar
  ["clinicas_medicas", "Clínicas médicas"],
  ["clinicas_odontologicas", "Clínicas odontológicas"],
  ["clinicas_veterinarias", "Clínicas veterinárias"],
  ["hospitais", "Hospitais"],
  ["farmacias", "Farmácias"],
  ["laboratorios", "Laboratórios"],
  ["psicologia", "Psicologia"],
  ["nutricao", "Nutrição"],
  ["fisioterapia", "Fisioterapia"],
  ["estetica", "Clínicas de estética"],
  ["saloes_beleza", "Salões de beleza"],
  ["spas", "Spas e centros de bem-estar"],
  ["academias", "Academias"],
  ["pilates_yoga", "Pilates e yoga"],
  ["home_care", "Home care e cuidados domiciliares"],
  ["optica", "Óticas"],
  ["ortopedia", "Clínicas de ortopedia"],
  ["cardiologia", "Clínicas de cardiologia"],
  ["dermatologia", "Clínicas de dermatologia"],
  // Educação
  ["escolas", "Escolas particulares"],
  ["cursos_profissionalizantes", "Cursos profissionalizantes"],
  ["faculdades", "Faculdades"],
  ["cursos_idiomas", "Cursos de idiomas"],
  ["cursos_ti", "Cursos de tecnologia"],
  ["preparatorios", "Cursos preparatórios"],
  ["creches", "Creches e educação infantil"],
  ["coaching", "Coaching e mentoria"],
  ["treinamentos_corporativos", "Treinamentos corporativos"],
  // Jurídico, contábil e consultoria
  ["advocacia", "Escritórios de advocacia"],
  ["contabilidade", "Contabilidade"],
  ["consultoria", "Consultorias"],
  ["consultoria_empresarial", "Consultoria empresarial"],
  ["consultoria_tributaria", "Consultoria tributária"],
  ["recursos_humanos", "Recursos humanos"],
  ["recrutamento", "Recrutamento e seleção"],
  ["seguros", "Seguradoras e corretores de seguros"],
  ["bancos", "Bancos"],
  ["fintechs", "Fintechs"],
  ["corretoras_investimentos", "Corretoras de investimentos"],
  ["cartorios", "Cartórios"],
  ["despachantes", "Despachantes"],
  // Imobiliário e construção
  ["imobiliarias", "Imobiliárias"],
  ["construtoras", "Construtoras"],
  ["incorporadoras", "Incorporadoras"],
  ["arquitetura", "Arquitetura"],
  ["engenharia", "Engenharia"],
  ["engenharia_civil", "Engenharia civil"],
  ["lojas_materiais_construcao", "Lojas de materiais de construção"],
  ["marcenarias", "Marcenarias"],
  ["serralherias", "Serralherias"],
  ["vidracarias", "Vidraçarias"],
  ["pintura_predial", "Pintura predial"],
  ["reformas_construcao", "Reformas e construção civil"],
  ["paisagismo", "Paisagismo"],
  ["administradoras_condominios", "Administradoras de condomínios"],
  // Assistência técnica e reparos
  ["assistencia_tecnica", "Assistência técnica"],
  ["assistencia_tecnica_computadores", "Assistência técnica de computadores"],
  ["assistencia_tecnica_notebooks", "Assistência técnica de notebooks"],
  ["assistencia_tecnica_celulares", "Assistência técnica de celulares"],
  ["assistencia_tecnica_tablets", "Assistência técnica de tablets"],
  ["assistencia_tecnica_impressoras", "Assistência técnica de impressoras"],
  ["assistencia_tecnica_tv", "Assistência técnica de TVs"],
  ["assistencia_tecnica_eletronicos", "Assistência técnica de eletrônicos"],
  ["assistencia_tecnica_videogames", "Assistência técnica de videogames"],
  ["assistencia_tecnica_cameras", "Assistência técnica de câmeras"],
  ["assistencia_tecnica_eletrodomesticos", "Assistência técnica de eletrodomésticos"],
  ["assistencia_tecnica_lavadoras", "Assistência técnica de máquinas de lavar"],
  ["assistencia_tecnica_refrigeradores", "Assistência técnica de refrigeradores"],
  ["assistencia_tecnica_microondas", "Assistência técnica de micro-ondas"],
  ["assistencia_tecnica_fornos", "Assistência técnica de fornos"],
  ["assistencia_tecnica_ar_condicionado", "Assistência técnica de ar-condicionado"],
  ["assistencia_tecnica_maquinas", "Assistência técnica de máquinas e equipamentos"],
  ["assistencia_tecnica_industrial", "Assistência técnica industrial"],
  ["assistencia_tecnica_medica", "Assistência técnica de equipamentos médicos"],
  ["assistencia_tecnica_automacao", "Assistência técnica de automação"],
  ["reparo_equipamentos", "Reparo de equipamentos eletrônicos"],
  ["manutencao_computadores", "Manutenção de computadores"],
  ["manutencao_notebooks", "Manutenção de notebooks"],
  ["manutencao_celulares", "Manutenção de celulares"],
  ["manutencao_impressoras", "Manutenção de impressoras"],
  ["manutencao_eletrodomesticos", "Manutenção de eletrodomésticos"],
  ["manutencao_ar_condicionado", "Manutenção de ar-condicionado"],
  ["reparos_eletricos", "Reparos elétricos"],
  ["reparos_hidraulicos", "Reparos hidráulicos"],
  // Automotivo e transporte
  ["concessionarias", "Concessionárias de veículos"],
  ["concessionarias_motos", "Concessionárias de motos"],
  ["oficinas", "Oficinas mecânicas"],
  ["autopecas", "Autopeças"],
  ["funilaria_pintura", "Funilaria e pintura"],
  ["guinchos", "Guinchos e reboque"],
  ["transportadoras", "Transportadoras"],
  ["logistica", "Empresas de logística"],
  ["motoboys", "Motoboys e entregas"],
  ["taxi_apps", "Táxi e apps de mobilidade"],
  ["estacionamentos", "Estacionamentos"],
  ["locadoras_veiculos", "Locadoras de veículos"],
  // Indústria e agro
  ["industria_metalurgica", "Metalúrgicas"],
  ["industria_textil", "Indústrias têxteis"],
  ["industria_alimenticia", "Indústrias alimentícias"],
  ["industria_moveleira", "Indústrias moveleiras"],
  ["industria_plastica", "Indústrias de plástico"],
  ["industria_quimica", "Indústrias químicas"],
  ["industria_farmaceutica", "Indústrias farmacêuticas"],
  ["agropecuaria", "Agropecuárias"],
  ["cooperativas", "Cooperativas"],
  ["distribuidoras", "Distribuidoras"],
  ["atacadistas", "Atacadistas"],
  ["embalagens", "Fabricantes de embalagens"],
  ["maquinas_equipamentos", "Máquinas e equipamentos"],
  // Varejo e comércio
  ["supermercados", "Supermercados"],
  ["lojas_moveis", "Lojas de móveis"],
  ["lojas_eletrodomesticos", "Lojas de eletrodomésticos"],
  ["moda", "Lojas de moda"],
  ["joalherias", "Joalherias"],
  ["pet_shops", "Pet shops"],
  ["papelarias", "Papelarias"],
  ["livrarias", "Livrarias"],
  ["lojas_esportivas", "Lojas esportivas"],
  ["loja_informatica", "Lojas de informática"],
  ["celulares", "Lojas de celulares"],
  ["otica_relojoaria", "Relojoarias"],
  ["floriculturas", "Floriculturas"],
  ["padarias", "Padarias e confeitarias"],
  ["acougues", "Açougues"],
  ["hortifruti", "Hortifruti"],
  // Alimentação e hospitalidade
  ["restaurantes", "Restaurantes"],
  ["bares", "Bares"],
  ["cafeterias", "Cafeterias"],
  ["lanchonetes", "Lanchonetes"],
  ["pizzarias", "Pizzarias"],
  ["food_trucks", "Food trucks"],
  ["buffets", "Buffets e catering"],
  ["hoteis", "Hotéis"],
  ["pousadas", "Pousadas"],
  ["turismo", "Agências de turismo"],
  ["resort", "Resorts"],
  ["airbnb_gestao", "Gestão de hospedagem"],
  // Serviços gerais
  ["limpeza", "Empresas de limpeza"],
  ["seguranca", "Segurança privada"],
  ["energia_solar", "Energia solar"],
  ["climatizacao", "Climatização e ar-condicionado"],
  ["eletricistas", "Serviços elétricos"],
  ["encanadores", "Encanadores e hidráulica"],
  ["jardinagem", "Jardinagem"],
  ["dedetizacao", "Dedetização"],
  ["lavanderias", "Lavanderias"],
  ["chaveiros", "Chaveiros"],
  ["mudancas", "Empresas de mudanças"],
  ["facilities", "Facilities e facilities management"],
  ["manutencao_predial", "Manutenção predial"],
  // Outros B2B relevantes
  ["coworking", "Coworkings"],
  ["impressao_3d", "Impressão 3D"],
  ["reciclagem", "Reciclagem e resíduos"],
  ["energia", "Distribuidoras de energia"],
  ["agua_saneamento", "Água e saneamento"],
  ["ong_fundacoes", "ONGs e fundações"],
  ["associacoes_comerciais", "Associações comerciais"],
  ["sindicatos", "Sindicatos"],
  ["franquias", "Franquias"],
  ["importadoras", "Importadoras"],
  ["exportadoras", "Exportadoras"],
  ["traducao", "Tradução e interpretação"],
  ["pesquisa_mercado", "Pesquisa de mercado"],
  ["call_center", "Call centers"],
  ["telemarketing", "Telemarketing"],
  ["auditoria", "Auditoria"],
  ["compliance", "Compliance e governança"],
  ["propriedade_intelectual", "Propriedade intelectual"],
  ["startups", "Startups"],
  ["incubadoras", "Incubadoras e aceleradoras"],
  ["venture_capital", "Venture capital e investidores"],
  ["contabilidade_digital", "Contabilidade digital"],
  ["software_gestao", "Software de gestão"],
  ["pdv_sistemas", "Sistemas de PDV"],
  ["automacao_industrial", "Automação industrial"],
  ["manutencao_industrial", "Manutenção industrial"],
  ["caldeiraria", "Caldeiraria"],
  ["usinagem", "Usinagem"],
  ["soldagem", "Soldagem"],
  ["transporte_escolar", "Transporte escolar"],
  ["fretamento", "Fretamento de ônibus"],
  ["armazenagem", "Armazenagem e estoque"],
  ["cross_docking", "Cross-docking"],
  ["comercio_exterior", "Comércio exterior"],
  ["despacho_aduaneiro", "Despacho aduaneiro"],
  ["certificacao_iso", "Certificação ISO"],
  ["meio_ambiente", "Consultoria ambiental"],
  ["seguranca_trabalho", "Segurança do trabalho"],
  ["medicina_trabalho", "Medicina do trabalho"],
  ["planos_saude", "Planos de saúde empresariais"],
  ["beneficios_rh", "Benefícios e RH"],
  ["uniformes", "Uniformes profissionais"],
  ["epi", "EPIs e segurança"],
  ["embalagens_industria", "Embalagens industriais"],
  ["quimicos_industriais", "Químicos industriais"],
  ["combustiveis", "Distribuidoras de combustíveis"],
  ["postos_gasolina", "Postos de gasolina"],
  ["lavagem_carros", "Lava-rápidos"],
  ["estetica_automotiva", "Estética automotiva"],
  ["blindagem", "Blindagem de veículos"],
  ["rastreamento", "Rastreamento veicular"],
  ["seguro_auto", "Seguro automotivo"],
  ["financiamento_veiculos", "Financiamento de veículos"],
];

export type BusinessNiche = (typeof BUSINESS_NICHES)[number];
